routes/web.php
<?php

use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['controller' => UserController::class], function () {
    Route::get('', 'home')->name('home');
    Route::post('','postLogin')->name('login');
    Route::get('register','register')->name('register');
    Route::post('register','postRegister')->name('register');
    // Route::get('home','home')->name('home');
    Route::get('detail/{id}','detail')->name('detail');
    Route::post('detail/{is}','postDetail')->name('detail');
    Route::get('bill','bill')->name('bill');
    Route::post('find/{id}','find');
    Route::get('getBill/{id}','getBill');
   
    Route::post('confirm/{id}','confirm')->name('confirm');
    Route::post('confirm-hd','postConfirm')->name('confirm-hd');

});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'controller' => AdminController::class], function () {
    Route::get('login','login')->name('login');
    Route::post('login','postlogin')->name('login');
    
    Route::get('', 'index')->name('index')->middleware('checkLogin');

    Route::post('filter-results', 'filterResult');

    // room
    Route::get('list-room', 'listRoom')->name('list-room');

    Route::get('empty-room', 'emptyRoom')->name('empty-room');

    Route::get('create-room', 'createRoom')->name('create-room');
    Route::post('create-room', 'postCreateRoom')->name('create-room');

    Route::get('edit-room/{id}', 'editRoom')->name('edit-room');
    Route::post('edit-room/{id}', 'postEditRoom')->name('edit-room');

    Route::post('delete-room/{id}','deleteRoom')->name('delete-room');
    Route::post('cancel/{id}','cancel')->name('cancel');

    Route::post('find/{id}','findHD');

    Route::post('start-room/{id}','startRoom');

    // product
    Route::get('list-product','listProduct')->name('list-product');
    Route::post('add-product','addProduct')->name('add-product');
    Route::post('edit-product','editProduct')->name('edit-product');

    Route::get('list-import-product', 'listImportProduct')->name('list-import-product');
    Route::get('import-product', 'importProduct')->name('import-product');
    Route::post('import-product', 'postImportProduct')->name('import-product');

    Route::get('list-export-product', 'listExportProduct')->name('list-export-product');
    Route::get('export-product/{id}', 'exportProduct')->name('export-product');
    Route::post('export-product/{id}', 'postExportProduct')->name('export-product');

    Route::get('hoadon/{id}','detailHd')->name('detailBill');

    Route::get('khach-hang','customer')->name('customer');

}); 

resources/views/admin/login.blade.php
<!doctype html>
<html lang="en" dir="ltr">

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <title>Hope UI | Responsive Bootstrap 5 Admin Dashboard Template</title>

   <!-- Favicon -->
   <link rel="shortcut icon" href="../../assets/images/favicon.ico" />

   <!-- Library / Plugin Css Build -->
   <link rel="stylesheet" href="../../assets/css/core/libs.min.css" />


   <!-- Hope Ui Design System Css -->
   <link rel="stylesheet" href="../../assets/css/hope-ui.min.css?v=2.0.0" />

   <!-- Custom Css -->
   <link rel="stylesheet" href="../../assets/css/custom.min.css?v=2.0.0" />

   <!-- Dark Css -->
   <link rel="stylesheet" href="../../assets/css/dark.min.css" />

   <!-- Customizer Css -->
   <link rel="stylesheet" href="../../assets/css/customizer.min.css" />

   <!-- RTL Css -->
   <link rel="stylesheet" href="../../assets/css/rtl.min.css" />


</head>

<body class=" " data-bs-spy="scroll" data-bs-target="#elements-section" data-bs-offset="0" tabindex="0">
   <!-- loader Start -->
   <div id="loading">
      <div class="loader simple-loader">
         <div class="loader-body"></div>
      </div>
   </div>
   <!-- loader END -->

   <div class="wrapper">
      <section class="login-content">
         <div class="row m-0 align-items-center bg-white vh-100">
            <div class="col-md-6">
               <div class="row justify-content-center">
                  <div class="col-md-10">
                     <div class="card card-transparent shadow-none d-flex justify-content-center mb-0 auth-card">
                        <div class="card-body">
                           <a href="../../dashboard/index.html" class="navbar-brand d-flex align-items-center mb-3">
                              <!--Logo start-->
                              <!--logo End-->

                              <!--Logo start-->
                              <div class="logo-main">
                                 <div class="logo-normal">
                                    <svg class="text-primary icon-30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                                       <rect x="-0.757324" y="19.2427" width="28" height="4" rx="2" transform="rotate(-45 -0.757324 19.2427)" fill="currentColor" />
                                       <rect x="7.72803" y="27.728" width="28" height="4" rx="2" transform="rotate(-45 7.72803 27.728)" fill="currentColor" />
                                       <rect x="10.5366" y="16.3945" width="16" height="4" rx="2" transform="rotate(45 10.5366 16.3945)" fill="currentColor" />
                                       <rect x="10.5562" y="-0.556152" width="28" height="4" rx="2" transform="rotate(45 10.5562 -0.556152)" fill="currentColor" />
                                    </svg>
                                 </div>
                                 <div class="logo-mini">
                                    <svg class="text-primary icon-30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                                       <rect x="-0.757324" y="19.2427" width="28" height="4" rx="2" transform="rotate(-45 -0.757324 19.2427)" fill="currentColor" />
                                       <rect x="7.72803" y="27.728" width="28" height="4" rx="2" transform="rotate(-45 7.72803 27.728)" fill="currentColor" />
                                       <rect x="10.5366" y="16.3945" width="16" height="4" rx="2" transform="rotate(45 10.5366 16.3945)" fill="currentColor" />
                                       <rect x="10.5562" y="-0.556152" width="28" height="4" rx="2" transform="rotate(45 10.5562 -0.556152)" fill="currentColor" />
                                    </svg>
                                 </div>
                              </div>
                              <!--logo End-->




                              <h4 class="logo-title ms-3">Hope UI</h4>
                           </a>
                           <h2 class="mb-2 text-center">Sign In</h2>
                           <p class="text-center">Login to stay connected.</p>
                           <form action="{{route('admin.login')}}" method="post">
                              @csrf
                              <div class="row">
                                 <div class="col-lg-12">
                                    <div class="form-group">
                                       <label for="email" class="form-label">Email</label>
                                       <input type="email" class="form-control" id="email" name="email" aria-describedby="email" placeholder=" ">
                                    </div>
                                 </div>
                                 <div class="col-lg-12">
                                    <div class="form-group">
                                       <label for="password" class="form-label">Password</label>
                                       <input type="password" class="form-control" id="password" name="password" aria-describedby="password" placeholder=" ">
                                    </div>
                                 </div>
                                 <div class="col-lg-12 d-flex justify-content-between">
                                    <div style="color: red">
                                       @error('error_login')
                                       {{$message}}
                                       @enderror
                                    </div>

                                 </div>
                              </div>
                              <div class="d-flex justify-content-center">
                                 <button type="submit" class="btn btn-primary">Sign In</button>
                              </div>
                              <p class="text-center my-3">or sign in with other accounts?</p>
                              <div class="d-flex justify-content-center">
                                 <ul class="list-group list-group-horizontal list-group-flush">
                                    <li class="list-group-item border-0 pb-0">
                                       <a href="#"><img src="../../assets/images/brands/fb.svg" alt="fb"></a>
                                    </li>
                                    <li class="list-group-item border-0 pb-0">
                                       <a href="#"><img src="../../assets/images/brands/gm.svg" alt="gm"></a>
                                    </li>
                                    <li class="list-group-item border-0 pb-0">
                                       <a href="#"><img src="../../assets/images/brands/im.svg" alt="im"></a>
                                    </li>
                                    <li class="list-group-item border-0 pb-0">
                                       <a href="#"><img src="../../assets/images/brands/li.svg" alt="li"></a>
                                    </li>
                                 </ul>
                              </div>
                              <p class="mt-3 text-center">
                                 Don’t have an account? <a href="sign-up.html" class="text-underline">Click here to sign up.</a>
                              </p>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="sign-bg">
                  <svg width="280" height="230" viewBox="0 0 431 398" fill="none" xmlns="http://www.w3.org/2000/svg">
                     <g opacity="0.05">
                        <rect x="-157.085" y="193.773" width="543" height="77.5714" rx="38.7857" transform="rotate(-45 -157.085 193.773)" fill="#3B8AFF" />
                        <rect x="7.46875" y="358.327" width="543" height="77.5714" rx="38.7857" transform="rotate(-45 7.46875 358.327)" fill="#3B8AFF" />
                        <rect x="61.9355" y="138.545" width="310.286" height="77.5714" rx="38.7857" transform="rotate(45 61.9355 138.545)" fill="#3B8AFF" />
                        <rect x="62.3154" y="-190.173" width="543" height="77.5714" rx="38.7857" transform="rotate(45 62.3154 -190.173)" fill="#3B8AFF" />
                     </g>
                  </svg>
               </div>
            </div>
            <div class="col-md-6 d-md-block d-none bg-primary p-0 mt-n1 vh-100 overflow-hidden">
               <img src="../../assets/images/auth/01.png" class="img-fluid gradient-main animated-scaleX" alt="images">
            </div>
         </div>
      </section>
   </div>

   <!-- Library Bundle Script -->
   <script src="../../assets/js/core/libs.min.js"></script>

   <!-- External Library Bundle Script -->
   <script src="../../assets/js/core/external.min.js"></script>

   <!-- Widgetchart Script -->
   <script src="../../assets/js/charts/widgetcharts.js"></script>

   <!-- mapchart Script -->
   <script src="../../assets/js/charts/vectore-chart.js"></script>
   <script src="../../assets/js/charts/dashboard.js"></script>

   <!-- fslightbox Script -->
   <script src="../../assets/js/plugins/fslightbox.js"></script>

   <!-- Settings Script -->
   <script src="../../assets/js/plugins/setting.js"></script>

   <!-- Slider-tab Script -->
   <script src="../../assets/js/plugins/slider-tabs.js"></script>

   <!-- Form Wizard Script -->
   <script src="../../assets/js/plugins/form-wizard.js"></script>

   <!-- AOS Animation Plugin-->

   <!-- App Script -->
   <script src="../../assets/js/hope-ui.js" defer></script>

</body>

</html>